changes

diff --git a/.github/workflows/deploy_uat_agents.yaml b/.github/workflows/deploy_uat_agents.yaml
--- a/.github/workflows/deploy_uat_agents.yaml
+++ b/.github/workflows/deploy_uat_agents.yaml
@@ -26,15 +26,27 @@ jobs:
 
       - name: Get Access Token
         id: get_token
-        run: echo "ACCESS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
+        run: echo "::add-mask::ACCESS_TOKEN=$(gcloud auth print-access-token)" >> $GITHUB_ENV
+
+      - name: print env
+        run: echo "API_HOST=${{ env.API_HOST }}"
 
       - name: Call Google Cloud API
         run: |
-          curl -f ${{ env.API_HOST }}/checkers \
+          response=$(curl -s -o response.json -w "%{http_code}" ${{ env.API_HOST }}/checkers \
             --header "Authorization: Bearer $ACCESS_TOKEN" \
             --header "Content-Type: application/json" \
-            -d '{"name": "'"$AGENT_NAME"'", "type": "ai", "telegramId": null}' \
-            -v
+            -v \
+            -d '{"name": "'"$AGENT_NAME"'", "type": "ai", "telegramId": null}')
+          if [ "$response" = "409" ]; then
+            echo "Name already exists, continuing..."
+          elif [ "$response" = "200" ]; then
+            echo "Successfully created agent, continuing..."
+          else
+            echo "API call failed with response code $response"
+            cat response.json
+            exit 1
+          fi
 
       - name: Deploy cloud function with pubsub trigger
         run: |
